// Copyright (c) 2026 TestNUX Contributors
// SPDX-License-Identifier: Apache-2.0

/**
 * test/codify.test.mjs
 *
 * Unit tests for `testnux codify` (src/commands/codify.mjs).
 *
 * All Anthropic API calls are mocked via vi.mock — no real API key required.
 * All file system side-effects write to a temp directory per test.
 *
 * Note on mocking strategy:
 *   codify.mjs uses a dynamic `import('@anthropic-ai/sdk')` inside runCodify().
 *   Vitest's vi.mock() hoisting intercepts this dynamic import at module
 *   evaluation time. We register the mock before the first import of codify.mjs.
 *
 * Note on folder strategy:
 *   runCodify uses `path.resolve('./testing-log')` for its default search.
 *   We pass an explicit --folder option pointing inside tmpDir so tests are
 *   isolated from any real testing-log/ on disk.
 */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import path from 'path';
import fs from 'fs';
import os from 'os';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);

// ── Module mock: @anthropic-ai/sdk ────────────────────────────────────────────
//
// vi.mock is hoisted to the top by Vitest — runs before any imports below.

const mockMessageCreate = vi.fn();

vi.mock('@anthropic-ai/sdk', () => ({
  default: class MockAnthropic {
    constructor() {
      this.messages = { create: mockMessageCreate };
    }
  },
}));

// ── Helpers ───────────────────────────────────────────────────────────────────

/** Builds a mock Anthropic API response object. */
function makeMockApiResponse(content, usage = { input_tokens: 2000, output_tokens: 1500 }) {
  return {
    id:            'msg_mock_codify_001',
    type:          'message',
    role:          'assistant',
    content:       [{ type: 'text', text: content }],
    model:         'claude-sonnet-4-6',
    stop_reason:   'end_turn',
    stop_sequence: null,
    usage,
  };
}

/** Builds a realistic mock test-plan.md that codify can parse. */
function makeMockTestPlan(slug = 'login', tcPrefix = 'LOGIN', tcCount = 2) {
  const frontmatter = `---
slug: ${slug}
title: ${slug.charAt(0).toUpperCase() + slug.slice(1)} Page [VERIFY]
industry: general
status: DRAFT
r_ids: []
tc_prefix: ${tcPrefix}
standards:
  - OWASP ASVS 4.0 v2.1.1
review_required: true
---`;

  const tcs = Array.from({ length: tcCount }, (_, i) => {
    const n = String(i + 1).padStart(2, '0');
    return `
## ${tcPrefix}-${n} — Valid login flow

| Field       | Value |
|-------------|-------|
| R-ID        | R-01 [VERIFY] |
| Priority    | P1 |
| Category    | FUNCTIONAL |
| Standards   | OWASP ASVS 2.1.1 |
| Status      | DRAFT |

**Preconditions**
- User is on the ${slug} page

**Steps**
1. Navigate to /${slug}
2. Enter valid email and password
3. Submit the form

**Expected Result**
The user is redirected to the dashboard.

**Evidence**
- [ ] Screenshot: \`evidence/${tcPrefix}-${n}-valid-login.png\`

> [VERIFY] Confirm R-ID mapping and expected result before execution.
`;
  }).join('\n');

  return frontmatter + '\n' + tcs;
}

/** Builds a realistic mock Playwright spec.ts response from the LLM. */
function makeMockSpec(slug = 'login', tcPrefix = 'LOGIN', tcCount = 2) {
  const imports = `// Copyright (c) 2026 TestNUX Contributors
// SPDX-License-Identifier: Apache-2.0
// [VERIFY] Generated by testnux codify v0.2 — review all selectors and assertions

import { test, expect, type Page, type Browser } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

const baseUrl = 'http://localhost:3000';

function xffForTest(title) {
  let hash = 0;
  for (let i = 0; i < title.length; i++) {
    hash = ((hash << 5) - hash + title.charCodeAt(i)) | 0;
  }
  const oct3 = Math.abs(hash >> 8) % 256;
  const oct4 = (Math.abs(hash) % 254) + 1;
  return \`10.99.\${oct3}.\${oct4}\`;
}

test.describe('${tcPrefix} — full test suite', () => {
  test.beforeEach(async ({ page }, testInfo) => {
    await page.setExtraHTTPHeaders({ 'X-Forwarded-For': xffForTest(testInfo.title) });
  });
`;

  const tests = Array.from({ length: tcCount }, (_, i) => {
    const n = String(i + 1).padStart(2, '0');
    return `
  test('${tcPrefix}-${n} — Valid login flow', async ({ page }) => {
    // Step 1: Navigate to /${slug}
    await page.goto(baseUrl + '/${slug}');
    await page.waitForLoadState('networkidle');

    // Step 2: Enter valid credentials
    await page.getByLabel('Email').fill('test@example.com');
    await page.getByLabel('Password').fill('password123');

    // Step 3: Submit form
    await page.evaluate(() => {
      const form = document.querySelector('form');
      form?.requestSubmit();
    });

    // [VERIFY] Selectors and assertions need human confirmation against the live page
    await expect(page).toHaveURL(baseUrl + '/dashboard');
  });
`;
  }).join('\n');

  return imports + tests + '\n});\n';
}

// ── Setup / teardown ──────────────────────────────────────────────────────────

let tmpDir;

beforeEach(() => {
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'codify-test-'));

  vi.clearAllMocks();

  // Default: successful API response with a valid spec
  mockMessageCreate.mockResolvedValue(makeMockApiResponse(makeMockSpec('login', 'LOGIN', 2)));
});

afterEach(() => {
  delete process.env.CLAUDE_API_KEY;

  try {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  } catch {
    // ignore cleanup errors
  }
});

// ── Import runCodify after mocks are established ──────────────────────────────

const { runCodify } = await import('../src/commands/codify.mjs');

// ── Helper: create a testing-log subfolder with test-plan.md ─────────────────

function makeTestingLogFolder(slug, planContent) {
  const folderName = `2026-04-27_${slug}`;
  const folderPath = path.join(tmpDir, folderName);
  fs.mkdirSync(folderPath, { recursive: true });
  fs.writeFileSync(path.join(folderPath, 'test-plan.md'), planContent, 'utf-8');
  return folderPath;
}

// ══════════════════════════════════════════════════════════════════════════════
// Tests
// ══════════════════════════════════════════════════════════════════════════════

describe('codify — missing CLAUDE_API_KEY', () => {
  it('throws with exitCode 1 when CLAUDE_API_KEY is not set', async () => {
    delete process.env.CLAUDE_API_KEY;
    const folder = makeTestingLogFolder('login', makeMockTestPlan('login', 'LOGIN'));

    let thrown;
    try {
      await runCodify('login', { folder, json: false });
    } catch (err) {
      thrown = err;
    }

    expect(thrown).toBeDefined();
    expect(thrown.exitCode).toBe(1);
    expect(thrown.message).toMatch(/CLAUDE_API_KEY/i);
  });

  it('JSON mode emits a codify.error event on stderr when API key missing', async () => {
    delete process.env.CLAUDE_API_KEY;
    const folder = makeTestingLogFolder('login', makeMockTestPlan('login', 'LOGIN'));

    const stderrLines = [];
    vi.spyOn(process.stderr, 'write').mockImplementation((chunk) => {
      stderrLines.push(String(chunk));
      return true;
    });

    try {
      await runCodify('login', { folder, json: true });
    } catch {
      // expected
    }

    const combined = stderrLines.join('');
    expect(combined.length).toBeGreaterThan(0);
    const parsed = JSON.parse(combined.trim().split('\n')[0]);
    expect(parsed.event).toBe('codify.error');
    expect(parsed.message).toMatch(/CLAUDE_API_KEY/i);
  });
});

describe('codify — missing @anthropic-ai/sdk guard (source inspection)', () => {
  it('source code contains ERR_MODULE_NOT_FOUND guard', () => {
    const src = fs.readFileSync(
      path.join(__dirname, '../src/commands/codify.mjs'),
      'utf-8',
    );
    expect(src).toContain('ERR_MODULE_NOT_FOUND');
    expect(src).toContain('npm install @anthropic-ai/sdk');
    expect(src).toContain('exitCode = 1');
  });

  it('source code uses dynamic import() for @anthropic-ai/sdk', () => {
    const src = fs.readFileSync(
      path.join(__dirname, '../src/commands/codify.mjs'),
      'utf-8',
    );
    expect(src).toContain("import('@anthropic-ai/sdk')");
    expect(src).not.toMatch(/^import\s+.*@anthropic-ai\/sdk/m);
  });
});

describe('codify — missing test-plan.md', () => {
  it('throws exitCode 1 when folder has no test-plan.md', async () => {
    process.env.CLAUDE_API_KEY = 'sk-ant-test-key';

    // Create folder but WITHOUT test-plan.md
    const folder = path.join(tmpDir, '2026-04-27_login');
    fs.mkdirSync(folder, { recursive: true });

    vi.spyOn(console, 'error').mockImplementation(() => {});

    let thrown;
    try {
      await runCodify('login', { folder, json: false });
    } catch (err) {
      thrown = err;
    }

    expect(thrown).toBeDefined();
    expect(thrown.exitCode).toBe(1);
    expect(thrown.message).toMatch(/test-plan\.md/i);
  });

  it('throws exitCode 1 when no testing-log folder exists for slug', async () => {
    process.env.CLAUDE_API_KEY = 'sk-ant-test-key';

    // Pass a non-existent folder explicitly
    const folder = path.join(tmpDir, 'nonexistent-folder');

    vi.spyOn(console, 'error').mockImplementation(() => {});

    let thrown;
    try {
      await runCodify('login', { folder, json: false });
    } catch (err) {
      thrown = err;
    }

    expect(thrown).toBeDefined();
    expect(thrown.exitCode).toBe(1);
  });
});

describe('codify — --dry-run', () => {
  it('does NOT call the Anthropic API', async () => {
    process.env.CLAUDE_API_KEY = 'sk-ant-test-key';
    const folder = makeTestingLogFolder('login', makeMockTestPlan('login', 'LOGIN'));

    await runCodify('login', { folder, dryRun: true, json: false });

    expect(mockMessageCreate).not.toHaveBeenCalled();
  });

  it('does NOT write spec.ts', async () => {
    process.env.CLAUDE_API_KEY = 'sk-ant-test-key';
    const folder = makeTestingLogFolder('login', makeMockTestPlan('login', 'LOGIN'));

    await runCodify('login', { folder, dryRun: true, json: false });

    expect(fs.existsSync(path.join(folder, 'spec.ts'))).toBe(false);
    expect(fs.existsSync(path.join(folder, 'spec.generated.ts'))).toBe(false);
  });

  it('prints SYSTEM PROMPT, USER PROMPT, and DRY-RUN COMPLETE', async () => {
    process.env.CLAUDE_API_KEY = 'sk-ant-test-key';
    const folder = makeTestingLogFolder('login', makeMockTestPlan('login', 'LOGIN'));

    const consoleLines = [];
    vi.spyOn(console, 'log').mockImplementation((...args) => {
      consoleLines.push(args.join(' '));
    });

    await runCodify('login', { folder, dryRun: true, json: false });

    const combined = consoleLines.join('\n');
    expect(combined).toContain('SYSTEM PROMPT');
    expect(combined).toContain('USER PROMPT');
    expect(combined).toContain('DRY-RUN COMPLETE');
    expect(combined).toContain('Estimated cost');
    expect(mockMessageCreate).not.toHaveBeenCalled();
  });

  it('--dry-run with --json emits a codify.dry-run event with cost estimate', async () => {
    process.env.CLAUDE_API_KEY = 'sk-ant-test-key';
    const folder = makeTestingLogFolder('login', makeMockTestPlan('login', 'LOGIN'));

    const stdoutLines = [];
    vi.spyOn(process.stdout, 'write').mockImplementation((chunk) => {
      stdoutLines.push(String(chunk));
      return true;
    });

    await runCodify('login', { folder, dryRun: true, json: true });

    expect(mockMessageCreate).not.toHaveBeenCalled();

    const parsed = JSON.parse(stdoutLines.join('').trim().split('\n')[0]);
    expect(parsed.event).toBe('codify.dry-run');
    expect(parsed.slug).toBe('login');
    expect(parsed).toHaveProperty('systemPrompt');
    expect(parsed).toHaveProperty('userPrompt');
    expect(parsed).toHaveProperty('costEstimateUsd');
    expect(parsed.costEstimateUsd).toBeGreaterThan(0);
  });
});

describe('codify — mock API success', () => {
  it('writes spec.ts with Playwright import and at least one test()', async () => {
    process.env.CLAUDE_API_KEY = 'sk-ant-test-key';
    const folder = makeTestingLogFolder('login', makeMockTestPlan('login', 'LOGIN'));

    await runCodify('login', { folder, json: false });

    const specPath = path.join(folder, 'spec.ts');
    expect(fs.existsSync(specPath)).toBe(true);

    const content = fs.readFileSync(specPath, 'utf-8');
    expect(content).toContain("from '@playwright/test'");
    expect(content).toMatch(/\btest\s*\(/);
  });

  it('calls the Anthropic API exactly once', async () => {
    process.env.CLAUDE_API_KEY = 'sk-ant-test-key';
    const folder = makeTestingLogFolder('login', makeMockTestPlan('login', 'LOGIN'));

    await runCodify('login', { folder, json: false });

    expect(mockMessageCreate).toHaveBeenCalledOnce();
  });

  it('--json emits a codify.done event with testCount, tokensIn, tokensOut, costUsd', async () => {
    process.env.CLAUDE_API_KEY = 'sk-ant-test-key';
    mockMessageCreate.mockResolvedValue(
      makeMockApiResponse(makeMockSpec('login', 'LOGIN', 2), { input_tokens: 2500, output_tokens: 1800 }),
    );
    const folder = makeTestingLogFolder('login', makeMockTestPlan('login', 'LOGIN'));

    const stdoutLines = [];
    vi.spyOn(process.stdout, 'write').mockImplementation((chunk) => {
      stdoutLines.push(String(chunk));
      return true;
    });

    await runCodify('login', { folder, json: true });

    const events = stdoutLines
      .join('')
      .trim()
      .split('\n')
      .filter(Boolean)
      .map((l) => JSON.parse(l));

    const done = events.find((e) => e.event === 'codify.done');
    expect(done).toBeDefined();
    expect(done.slug).toBe('login');
    expect(done.testCount).toBeGreaterThan(0);
    expect(done.tokensIn).toBe(2500);
    expect(done.tokensOut).toBe(1800);
    expect(done.costUsd).toBeGreaterThan(0);
    expect(done.outFile).toContain('spec');
  });
});

describe('codify — [VERIFY] auto-injection', () => {
  it('injects [VERIFY] on test() blocks that are missing it', async () => {
    process.env.CLAUDE_API_KEY = 'sk-ant-test-key';

    // Build a spec that has no [VERIFY] comments in any test() block
    const specWithoutVerify = `// Copyright (c) 2026 TestNUX Contributors
// SPDX-License-Identifier: Apache-2.0

import { test, expect, type Page, type Browser } from '@playwright/test';

const baseUrl = 'http://localhost:3000';

test.describe('LOGIN — full test suite', () => {
  test('LOGIN-01 — Valid login flow', async ({ page }) => {
    await page.goto(baseUrl + '/login');
    await expect(page).toHaveURL(baseUrl + '/login');
  });
});
`;

    mockMessageCreate.mockResolvedValue(makeMockApiResponse(specWithoutVerify));
    const folder = makeTestingLogFolder('login', makeMockTestPlan('login', 'LOGIN'));

    await runCodify('login', { folder, json: false });

    const content = fs.readFileSync(path.join(folder, 'spec.ts'), 'utf-8');
    expect(content).toContain('[VERIFY]');
  });
});

describe('codify — --safe flag', () => {
  it('writes spec.generated.ts instead of spec.ts when --safe is set and spec.ts already exists', async () => {
    process.env.CLAUDE_API_KEY = 'sk-ant-test-key';
    const folder = makeTestingLogFolder('login', makeMockTestPlan('login', 'LOGIN'));

    // Pre-create a spec.ts WITH [VERIFY] markers so it's not treated as hand-edited
    // The safe flag should still route output to spec.generated.ts
    const existingSpec = `import { test, expect } from '@playwright/test';
// [VERIFY] existing spec
test('LOGIN-01', async ({ page }) => {
  // [VERIFY] placeholder
  await expect(page.locator('body')).toBeVisible();
});
`;
    fs.writeFileSync(path.join(folder, 'spec.ts'), existingSpec, 'utf-8');

    await runCodify('login', { folder, safe: true, json: false });

    // With --safe and spec.ts existing, output goes to spec.generated.ts
    expect(fs.existsSync(path.join(folder, 'spec.generated.ts'))).toBe(true);
  });

  it('codify.done event reports outFile ending in spec.generated.ts when --safe + existing spec.ts', async () => {
    process.env.CLAUDE_API_KEY = 'sk-ant-test-key';
    const folder = makeTestingLogFolder('login', makeMockTestPlan('login', 'LOGIN'));

    // Pre-create spec.ts with [VERIFY] so not hand-edited, but --safe still redirects
    const existingSpec = `import { test, expect } from '@playwright/test';
// [VERIFY] existing spec
test('LOGIN-01', async ({ page }) => {
  // [VERIFY] check
  await expect(page.locator('body')).toBeVisible();
});
`;
    fs.writeFileSync(path.join(folder, 'spec.ts'), existingSpec, 'utf-8');

    const stdoutLines = [];
    vi.spyOn(process.stdout, 'write').mockImplementation((chunk) => {
      stdoutLines.push(String(chunk));
      return true;
    });

    await runCodify('login', { folder, safe: true, json: true });

    const events = stdoutLines
      .join('')
      .trim()
      .split('\n')
      .filter(Boolean)
      .map((l) => JSON.parse(l));

    const done = events.find((e) => e.event === 'codify.done');
    expect(done).toBeDefined();
    expect(done.outFile).toContain('spec.generated.ts');
  });
});

describe('codify — hand-edit detection', () => {
  it('writes spec.generated.ts when existing spec.ts has no [VERIFY] markers', async () => {
    process.env.CLAUDE_API_KEY = 'sk-ant-test-key';
    const folder = makeTestingLogFolder('login', makeMockTestPlan('login', 'LOGIN'));

    // Place a spec.ts without any [VERIFY] markers (simulates hand-edited file)
    const handEdited = `import { test, expect } from '@playwright/test';

test.describe('LOGIN suite', () => {
  test('LOGIN-01 — Valid login', async ({ page }) => {
    await page.goto('http://localhost:3000/login');
    await expect(page).toHaveURL('http://localhost:3000/dashboard');
  });
});
`;
    fs.writeFileSync(path.join(folder, 'spec.ts'), handEdited, 'utf-8');

    const consoleLines = [];
    vi.spyOn(console, 'log').mockImplementation((...args) => {
      consoleLines.push(args.join(' '));
    });

    await runCodify('login', { folder, json: false });

    // Should write to spec.generated.ts, not overwrite spec.ts
    expect(fs.existsSync(path.join(folder, 'spec.generated.ts'))).toBe(true);

    // Warning should be printed
    expect(consoleLines.join('\n')).toMatch(/hand-edit|spec\.generated/i);
  });

  it('codify.done event reports handEdited: true for hand-edited file', async () => {
    process.env.CLAUDE_API_KEY = 'sk-ant-test-key';
    const folder = makeTestingLogFolder('login', makeMockTestPlan('login', 'LOGIN'));

    // Hand-edited spec.ts (no [VERIFY])
    const handEdited = `import { test, expect } from '@playwright/test';
test('LOGIN-01', async ({ page }) => {
  await expect(page.locator('body')).toBeVisible();
});
`;
    fs.writeFileSync(path.join(folder, 'spec.ts'), handEdited, 'utf-8');

    const stdoutLines = [];
    vi.spyOn(process.stdout, 'write').mockImplementation((chunk) => {
      stdoutLines.push(String(chunk));
      return true;
    });

    await runCodify('login', { folder, json: true });

    const events = stdoutLines
      .join('')
      .trim()
      .split('\n')
      .filter(Boolean)
      .map((l) => JSON.parse(l));

    const done = events.find((e) => e.event === 'codify.done');
    expect(done).toBeDefined();
    expect(done.handEdited).toBe(true);
    expect(done.outFile).toContain('spec.generated.ts');
  });
});

describe('codify — mock parse error (LLM returns non-TypeScript)', () => {
  it('saves spec.raw.txt and throws with exitCode 3', async () => {
    process.env.CLAUDE_API_KEY = 'sk-ant-test-key';
    const folder = makeTestingLogFolder('login', makeMockTestPlan('login', 'LOGIN'));

    const garbledResponse = 'Here is a summary of your test plan. I cannot generate TypeScript code right now.';
    mockMessageCreate.mockResolvedValue(makeMockApiResponse(garbledResponse));

    vi.spyOn(console, 'error').mockImplementation(() => {});

    let thrown;
    try {
      await runCodify('login', { folder, json: false });
    } catch (err) {
      thrown = err;
    }

    expect(thrown).toBeDefined();
    expect(thrown.exitCode).toBe(3);

    const rawFile = path.join(folder, 'spec.raw.txt');
    expect(fs.existsSync(rawFile)).toBe(true);
    expect(fs.readFileSync(rawFile, 'utf-8')).toBe(garbledResponse);
  });

  it('empty LLM response → exitCode 3 + spec.raw.txt written', async () => {
    process.env.CLAUDE_API_KEY = 'sk-ant-test-key';
    const folder = makeTestingLogFolder('login', makeMockTestPlan('login', 'LOGIN'));

    mockMessageCreate.mockResolvedValue(makeMockApiResponse(''));

    vi.spyOn(console, 'error').mockImplementation(() => {});

    let thrown;
    try {
      await runCodify('login', { folder, json: false });
    } catch (err) {
      thrown = err;
    }

    expect(thrown).toBeDefined();
    expect(thrown.exitCode).toBe(3);
  });
});

describe('codify — JSON output mode', () => {
  it('done event has required NDJSON shape fields', async () => {
    process.env.CLAUDE_API_KEY = 'sk-ant-test-key';
    mockMessageCreate.mockResolvedValue(
      makeMockApiResponse(makeMockSpec('login', 'LOGIN', 2), { input_tokens: 1000, output_tokens: 800 }),
    );
    const folder = makeTestingLogFolder('login', makeMockTestPlan('login', 'LOGIN'));

    const stdoutLines = [];
    vi.spyOn(process.stdout, 'write').mockImplementation((chunk) => {
      stdoutLines.push(String(chunk));
      return true;
    });

    await runCodify('login', { folder, json: true });

    const events = stdoutLines
      .join('')
      .trim()
      .split('\n')
      .filter(Boolean)
      .map((l) => JSON.parse(l));

    const done = events.find((e) => e.event === 'codify.done');
    expect(done).toBeDefined();
    expect(typeof done.slug).toBe('string');
    expect(typeof done.folder).toBe('string');
    expect(typeof done.outFile).toBe('string');
    expect(typeof done.tcCount).toBe('number');
    expect(typeof done.testCount).toBe('number');
    expect(typeof done.tokensIn).toBe('number');
    expect(typeof done.tokensOut).toBe('number');
    expect(typeof done.costUsd).toBe('number');
    expect(typeof done.handEdited).toBe('boolean');
  });
});

describe('codify — mock API 429 rate limit', () => {
  it('throws with exitCode 2', async () => {
    process.env.CLAUDE_API_KEY = 'sk-ant-test-key';
    const folder = makeTestingLogFolder('login', makeMockTestPlan('login', 'LOGIN'));

    mockMessageCreate.mockRejectedValue(
      Object.assign(new Error('Rate limit exceeded'), {
        status:  429,
        headers: { 'retry-after': '30' },
      }),
    );

    vi.spyOn(console, 'error').mockImplementation(() => {});

    let thrown;
    try {
      await runCodify('login', { folder, json: false });
    } catch (err) {
      thrown = err;
    }

    expect(thrown).toBeDefined();
    expect(thrown.exitCode).toBe(2);
  });

  it('error output mentions 429 or rate limit and retry', async () => {
    process.env.CLAUDE_API_KEY = 'sk-ant-test-key';
    const folder = makeTestingLogFolder('login', makeMockTestPlan('login', 'LOGIN'));

    mockMessageCreate.mockRejectedValue(
      Object.assign(new Error('Rate limit exceeded'), {
        status:  429,
        headers: { 'retry-after': '60' },
      }),
    );

    const errorLines = [];
    vi.spyOn(console, 'error').mockImplementation((...args) => {
      errorLines.push(args.join(' '));
    });

    try {
      await runCodify('login', { folder, json: false });
    } catch {
      // expected
    }

    expect(errorLines.join('\n')).toMatch(/429|rate limit/i);
    expect(errorLines.join('\n')).toMatch(/retry/i);
  });
});

describe('codify — --max-spend enforcement', () => {
  it('aborts BEFORE API call when cost estimate exceeds --max-spend', async () => {
    process.env.CLAUDE_API_KEY = 'sk-ant-test-key';
    const folder = makeTestingLogFolder('login', makeMockTestPlan('login', 'LOGIN'));

    vi.spyOn(console, 'error').mockImplementation(() => {});

    let thrown;
    try {
      await runCodify('login', {
        folder,
        maxSpend: 0.0001, // absurdly low — estimate will exceed this
        json:     false,
      });
    } catch (err) {
      thrown = err;
    }

    expect(thrown).toBeDefined();
    expect(thrown.exitCode).toBe(1);
    expect(thrown.message).toMatch(/max-spend/i);
    // Critical: must NOT have called the API
    expect(mockMessageCreate).not.toHaveBeenCalled();
  });

  it('proceeds to API call when estimated cost is within --max-spend 100', async () => {
    process.env.CLAUDE_API_KEY = 'sk-ant-test-key';
    const folder = makeTestingLogFolder('login', makeMockTestPlan('login', 'LOGIN'));

    await runCodify('login', {
      folder,
      maxSpend: 100,
      json:     false,
    });

    expect(mockMessageCreate).toHaveBeenCalledOnce();
  });
});
