// Copyright (c) 2026 TestNUX Contributors
// SPDX-License-Identifier: Apache-2.0

/**
 * src/commands/codify.mjs
 *
 * Implements `testnux codify <slug>`.
 *
 * v0.1 STUB — describes what the v0.2 LLM agent will do and provides the
 * Playwright spec.ts scaffold. No LLM calls are made.
 *
 * v0.2 plan:
 *   1. Read testing-log/<date>_<slug>/test-plan.md.
 *   2. Parse all TC-XX sections (title, steps, evidence checklist, priority).
 *   3. Send to Claude with the prompt template below.
 *   4. Receive fully typed Playwright spec.ts.
 *   5. Write to testing-log/<date>_<slug>/spec.ts.
 *   6. [VERIFY] comment on every generated assertion.
 *
 * Cost estimate (v0.2): ~$0.20–$0.60 per page. Requires CLAUDE_API_KEY.
 *
 * =============================================================================
 * V0.2 PROMPT TEMPLATE (for implementers):
 * =============================================================================
 *
 * SYSTEM:
 *   You are a senior QA automation engineer specializing in Playwright TypeScript.
 *   You write tests that are:
 *     - Deterministic: no time.sleep(), no arbitrary waits; use waitFor*() APIs
 *     - Resilient: prefer getByRole() and getByLabel() over CSS selectors
 *     - Documented: every test body has an inline comment per step
 *     - Evidence-collecting: afterEach() saves a screenshot to evidence/
 *     - Typed: strict TypeScript, no `any` except where Playwright types require it
 *   You ALWAYS wrap generated assertions with a // [VERIFY] comment.
 *   You NEVER assume implementation details — use only what the test plan states.
 *
 * USER:
 *   Surface slug: {{slug}}
 *   Base URL: {{base_url}}
 *   Test plan:
 *   ---
 *   {{test_plan_md}}
 *   ---
 *
 *   TASK: Generate a Playwright TypeScript spec.ts for this surface.
 *
 *   OUTPUT REQUIREMENTS:
 *
 *   1. File header (required):
 *      // Copyright (c) [year] [org]
 *      // SPDX-License-Identifier: [license]
 *      // [VERIFY] Generated by testnux codify v0.2 — review all assertions
 *
 *   2. Imports (required):
 *      import { test, expect } from '@playwright/test';
 *
 *   3. One test.describe() block per page section in the test plan.
 *
 *   4. One test() per TC-XX. Naming: test('{{TC_PREFIX}}-NN — [title from plan]', ...)
 *
 *   5. Inside each test:
 *      a. Navigate if needed: await page.goto(BASE_URL + '/path');
 *      b. One comment per step from the plan: // Step N: [step text]
 *      c. Action: await page.getByRole(...) or getByLabel(...)
 *      d. Assertion: // [VERIFY] confirm expected result per test plan
 *                    await expect(page.getByRole(...)).toBeVisible();
 *      e. Evidence: await page.screenshot({ path: 'evidence/{{TC_PREFIX}}-NN.png' });
 *
 *   6. afterEach() hook at describe-block level:
 *      test.afterEach(async ({ page }, testInfo) => {
 *        if (testInfo.status !== testInfo.expectedStatus) {
 *          const name = testInfo.title.replace(/[^a-z0-9]/gi, '-');
 *          await page.screenshot({ path: `evidence/${name}-FAIL.png`, fullPage: true });
 *        }
 *      });
 *
 *   7. P0 tests run first (use test.describe.configure({ mode: 'serial' }) for P0 group).
 *
 *   CRITICAL RULES:
 *   - Use page.getByRole() and page.getByLabel() — not CSS selectors unless unavoidable
 *   - Use await expect(locator).toBeVisible() not .toBeTruthy() on DOM nodes
 *   - Never use page.waitForTimeout() — use page.waitForLoadState() or locator.waitFor()
 *   - Every assertion gets a // [VERIFY] comment
 *   - Include only TCs present in the test plan — do not invent new ones
 *   - Output TypeScript (strict mode compatible). No `any` unless from Playwright types.
 *
 * =============================================================================
 */

import path from 'path';
import fs from 'fs';

// ── Public API ───────────────────────────────────────────────────────────────

/**
 * @param {string} slug  Surface slug (e.g. "login")
 * @param {{
 *   baseUrl:  string | undefined,
 *   out:      string | undefined,
 *   json:     boolean,
 * }} opts
 */
export async function runCodify(slug, opts = {}) {
  const {
    baseUrl = 'http://localhost:3000',
    out     = './testing-log',
    json    = false,
  } = opts;

  log(json, { event: 'codify.stub', slug, baseUrl, version: 'v0.1' });

  const testPlanFile = findTestPlanFile(slug, out);

  if (!json) {
    console.log('');
    console.log('  testnux codify — v0.1 stub');
    console.log('  ─────────────────────────────────────────────────────────');
    console.log(`  Slug     : ${slug}`);
    console.log(`  Base URL : ${baseUrl}`);
    console.log('');
    console.log('  In v0.2, this command will:');
    console.log('    1. Read testing-log/<date>_<slug>/test-plan.md.');
    console.log('    2. Parse all TC-XX sections (title, steps, priority,');
    console.log('       evidence checklist).');
    console.log('    3. Send to Claude with a prompt that enforces strict');
    console.log('       Playwright TypeScript conventions:');
    console.log('       - getByRole() / getByLabel() — not CSS selectors');
    console.log('       - waitFor*() — never waitForTimeout()');
    console.log('       - afterEach() screenshot hook for FAIL evidence');
    console.log('       - [VERIFY] comment on every generated assertion');
    console.log('    4. Write testing-log/<date>_<slug>/spec.ts.');
    console.log('    5. Cost: ~$0.20–$0.60 per page. Requires CLAUDE_API_KEY.');
    console.log('');

    if (testPlanFile) {
      console.log(`  Found test plan: ${testPlanFile}`);
      console.log('');
      console.log('  For now, use the scaffolded spec.ts from `testnux init`');
      console.log('  and implement each test manually following the plan steps.');
    } else {
      console.log(`  No test plan found for slug "${slug}".`);
      console.log('');
      console.log('  Suggested workflow:');
      console.log(`    1. testnux discover <url>    # generate scenarios`);
      console.log(`    2. testnux plan ${slug}      # generate test-plan.md`);
      console.log(`    3. testnux init ${slug}      # scaffold spec.ts`);
      console.log(`    4. testnux codify ${slug}    # (v0.2) generates spec.ts from plan`);
    }

    console.log('');
    console.log('  See the prompt template in src/commands/codify.mjs for the');
    console.log('  exact Claude prompt that v0.2 will use.');
    console.log('');
  } else {
    process.stdout.write(
      JSON.stringify({
        event:         'codify.stub.done',
        slug,
        baseUrl,
        testPlanFile:  testPlanFile ?? null,
        message:       'v0.1 stub — see v0.2 roadmap for LLM-powered spec generation',
      }) + '\n',
    );
  }
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function findTestPlanFile(slug, outDir) {
  const testingLog = path.resolve(outDir);
  if (!fs.existsSync(testingLog)) return null;

  for (const entry of fs.readdirSync(testingLog).sort().reverse()) {
    if (entry.includes(slug)) {
      const f = path.join(testingLog, entry, 'test-plan.md');
      if (fs.existsSync(f)) return f;
    }
  }
  return null;
}

function log(json, payload) {
  if (json) process.stdout.write(JSON.stringify(payload) + '\n');
}
